apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../nncp

nameSuffix: "-1"

patches:
  - target:
      group: nmstate.io
      version: v1
      kind: NodeNetworkConfigurationPolicy
    patch: |-
      - op: replace
        path: "/spec/nodeSelector/kubernetes.io~1hostname"
        value: worker-1
