apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/openstack-gitops/rhoso-gitops/base/lvms-operator

patches:
  - target:
      kind: LVMCluster
    path: patches/lvmcluster-default.yaml
