apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: openstack-lvm-storage
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      patches:
      - patch: |-
          - op: add
            path: /metadata/labels
            value:
              argocd.argoproj.io/managed-by: openshift-gitops
        target:
          kind: Namespace
    path: datacenter/rhoso18/storage
    repoURL: https://github.com/openstack-gitops/environments.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}

